export { default as first } from './firstPage/firstPage'
export { default as second } from './secondPage/secondPage'
export { default as third } from './thirdPage/thirdPage'
export { default as foruth } from './fourthPage/fourthPage'
export { default as aside } from './aside/aside'